sudo: required

services:
  - docker

addons:
  firefox: "30.0"
    
language: ruby

rvm:
  - "2.0.0"
  
env:
  DOCKER_COMPOSE_VERSION: 1.8.0
  global:
    - CI_NODE_TOTAL=5
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - CI_NODE_INDEX=4

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
  - docker-compose --version
  - docker-compose up -d
  - docker-compose ps
#  - sudo rm /usr/local/bin/docker-compose
#  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#  - chmod +x docker-compose
#  - sudo mv docker-compose /usr/local/bin
#  - sudo docker-compose --version

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq flashplugin-installer
  - "gem install cucumber"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start --server-args="-screen 0 1024x768x24"

script: "bundle exec rake play"


#script:
#- "bundle exec rake knapsack:features"
#- "KNAPSACK_GENERATE_REPORT=true bundle exec rake features"
